name: Notion Random Review

on:
  schedule:
    - cron: "0 1 * * *"   # chạy mỗi ngày 08:00 VN (UTC+7)
  workflow_dispatch:      # cho phép bấm Run tay

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - run: npm install node-fetch

      - run: node random_review.js
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
